// FETCH BILLS
export const FETCH_BILLS_REQUEST = "FETCH_BILLS_REQUEST";
export const FETCH_BILLS_SUCCESS = "FETCH_BILLS_SUCCESS";
export const FETCH_BILLS_FAILED = "FETCH_BILLS_FAILED";

// CREATE BILLS
export const CREATE_BILLS_REQUEST = "CREATE_BILLS_REQUEST";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAILED = "CREATE_BILL_FAILED";
