// FETCH BILLS
export const FETCH_BILLS_REQUEST = "FETCH_BILLS_REQUEST";
export const FETCH_BILLS_SUCCESS = "FETCH_BILLS_SUCCESS";
export const FETCH_BILLS_FAILED = "FETCH_BILLS_FAILED";

// CREATE BILLS
export const CREATE_BILLS_REQUEST = "CREATE_BILLS_REQUEST";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAILED = "CREATE_BILL_FAILED";

// Delete BILLS
export const DELETE_BILLS_REQUEST = "DELETE_BILLS_REQUEST";
export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";
export const DELETE_BILL_FAILED = "DELETE_BILL_FAILED";

// Change Status
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
